# Generated by Django 4.2.30 on 2026-05-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='bio',
        ),
        migrations.AddField(
            model_name='speaker',
            name='cv_image',
            field=models.ImageField(blank=True, null=True, upload_to='speakers/cvs/'),
        ),
    ]
