# Generated by Django 4.2.16 on 2026-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_price_event_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ccp_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
