# Generated by Django 4.2.16 on 2026-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="payment_receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AddField(
            model_name="registration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
