# Generated by Django 4.2.16 on 2026-03-14 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_price_event_ticket_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("participants", "0002_registration_payment_receipt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhibitorStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stand_type",
                    models.CharField(
                        choices=[
                            ("minimum", "Minimum"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("payment_receipt", models.FileField(upload_to="exhibitor_receipts/")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitor_stands",
                        to="events.event",
                    ),
                ),
                (
                    "exhibitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitor_stands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "exhibitor")},
            },
        ),
    ]
